module.exports = (app) => {
  app.on('issue_comment.created', async (context) => {
    const commentBody = context.payload.comment.body.trim();
    const issue = context.payload.issue;

    // Check if the comment contains the /assign command
    if (commentBody.startsWith('/assign')) {
      let assignee = context.payload.comment.user.login; // Default to assigning the commenter

      // Check for specific user mention (e.g., /assign @username)
      const match = commentBody.match(/\/assign @(\S+)/);
      if (match) {
        assignee = match[1];
      }

      // Add the assignee to the issue or pull request
      try {
        await context.octokit.issues.addAssignees({
          owner: context.repo().owner,
          repo: context.repo().repo,
          issue_number: issue.number,
          assignees: [assignee],
        });
        context.log.info(`Assigned issue #${issue.number} to ${assignee}`);
      } catch (error) {
        context.log.error('Failed to assign:', error);
      }
    }
  });
};
